### ISSUE TITLE
这里会跟进新版本吗？

### ISSUE THREAD

**Issue by 70599** [sfantree/trojan-armv6#1]

**Comment by sfantree** [comment]
整个打包过程都在readme，可以参考自行编译。
现在trojan的功能基本稳定，没有特殊需求不会更新。
这个项目主要是解决trojan在树莓派的使用问题，现在已经解决了。另外最新的clash已经实现了trojan的支持，并且golang跨平台更方便

**Comment by 70599** [comment]
知道了，感谢回复
